// app/layout.jsx
import "./globals.css";
import { Be_Vietnam_Pro } from "next/font/google";

const bevn = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["400", "700"], // Regular + Bold
});

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body className={bevn.className}>
        {children}
      </body>
    </html>
  );
}
