// app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Geist.className} ${Geist_Mono.className}`}>
        {children}
      </body>
    </html>
  );
}
